"""Dashboard data layer for cross-project session management."""

from .models import (
    DashboardConfig,
    DashboardSettings,
    ProjectRegistration,
    ProjectState,
    RoadmapSummary,
    Session,
    SessionStatus,
)
from .notify import (
    check_and_notify,
    get_long_parked_sessions,
)
from .store import (
    add_event,
    build_overview,
    complete_session,
    create_session,
    get_active_sessions,
    get_all_project_states,
    get_parked_sessions,
    get_project_state,
    get_registered_projects,
    get_session,
    get_stale_sessions,
    heartbeat,
    heartbeat_project,
    list_sessions,
    load_config,
    park_session,
    register_project,
    resume_session,
    update_project_state,
    update_session,
)

__all__ = [
    "DashboardConfig",
    "DashboardSettings",
    "ProjectRegistration",
    "ProjectState",
    "RoadmapSummary",
    "Session",
    "SessionStatus",
    "add_event",
    "build_overview",
    "check_and_notify",
    "complete_session",
    "create_session",
    "get_active_sessions",
    "get_all_project_states",
    "get_long_parked_sessions",
    "get_parked_sessions",
    "get_project_state",
    "get_registered_projects",
    "get_session",
    "get_stale_sessions",
    "heartbeat",
    "heartbeat_project",
    "list_sessions",
    "load_config",
    "park_session",
    "register_project",
    "resume_session",
    "update_project_state",
    "update_session",
]
